2024-08-01 18:49:12,590 mloop                INFO     M-LOOP version 3.3.4
2024-08-01 18:49:12,590 mloop                DEBUG    M-LOOP Logger configured.
2024-08-01 18:49:12,590 mloop.interfaces     DEBUG    Creating interface.
2024-08-01 18:49:12,590 mloop.controllers    DEBUG    Controller init completed.
2024-08-01 18:49:12,590 mloop.learners.1     DEBUG    Learner init completed.
2024-08-01 18:49:12,590 mloop.learners.2     DEBUG    Learner init completed.
2024-08-01 18:49:12,590 mloop.controllers    INFO     Optimization started.
2024-08-01 18:49:12,597 mloop.interfaces     DEBUG    Entering main loop of interface.
2024-08-01 18:49:12,598 mloop.controllers    DEBUG    ML learner started.
2024-08-01 18:49:12,660 mloop.controllers    DEBUG    Starting training optimization.
2024-08-01 18:49:12,660 mloop.controllers    INFO     Run: 0 (training)
2024-08-01 18:49:12,663 mloop.controllers    INFO     params [ 5.11058298 26.31148865  0.17446492 14.7622242   2.61499655]
2024-08-01 18:49:27,132 mloop.interfaces     DEBUG    Interface ended
2024-08-01 18:49:27,736 mloop.controllers    ERROR    The interface raised an error with traceback:
  File "c:\Users\jarjarbinks\.venv\kpy\lib\site-packages\mloop\interfaces.py", line 133, in run
    cost_dict = self.get_next_cost_dict(params_dict)

  File "c:\Users\jarjarbinks\code\k-exp\kexp\experiments\Mloop testing\integration\lib.py", line 168, in get_next_cost_dict
    cost = getCost()

  File "c:\Users\jarjarbinks\code\k-exp\kexp\experiments\Mloop testing\integration\lib.py", line 30, in getCost
    atomnumber = getAtomNumber()

  File "c:\Users\jarjarbinks\code\k-exp\kexp\experiments\Mloop testing\integration\lib.py", line 25, in getAtomNumber
    ad = load_atomdata(0,crop_type='gm',average_repeats = True)

  File "c:\users\jarjarbinks\code\k-exp\kexp\util\data\load_atomdata.py", line 71, in load_atomdata
    ad = atomdata(xvarnames,images,image_timestamps,params,camera_params,run_info,

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\atomdata.py", line 71, in __init__
    self.analyze_ods()

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\atomdata.py", line 260, in analyze_ods
    self._analyze_absorption_images(crop_type)

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\atomdata.py", line 297, in _analyze_absorption_images
    self.od, self.sum_od_x, self.sum_od_y = process_ODs(self.od_raw, crop_type, self.Nvars)

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\image_processing\compute_ODs.py", line 30, in process_ODs
    ODs = roi.crop_OD(raw_ODs,crop_type,Nvars)

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\image_processing\roi_select.py", line 73, in crop_OD
    return cropOD

2024-08-01 18:49:27,736 mloop.controllers    WARNING  Controller ended due to exception of some kind. Starting shut down...
2024-08-01 18:49:27,736 mloop.controllers    DEBUG    ML learner end set.
2024-08-01 18:49:28,285 mloop.controllers    DEBUG    ML learner joined
2024-08-01 18:49:28,285 mloop.controllers    INFO     Machine learning learner did not provide best and/or all minima.
2024-08-01 18:49:28,286 mloop.controllers    DEBUG    Learner end event set.
2024-08-01 18:49:28,286 mloop.controllers    DEBUG    Interface end event set.
2024-08-01 18:49:28,663 mloop.learners.1     DEBUG    Learner end signal received. Ending
2024-08-01 18:49:29,669 mloop.controllers    DEBUG    Learner joined.
2024-08-01 18:49:29,669 mloop.controllers    DEBUG    Interface joined.
2024-08-01 18:49:29,670 mloop.controllers    WARNING  Safely shut down. Below are results found before exception.
2024-08-01 18:49:29,671 mloop.controllers    INFO     Optimization ended because:
2024-08-01 18:49:29,672 mloop.controllers    INFO     	* Error occurred.
2024-08-01 18:49:29,673 mloop.controllers    INFO     Results:
2024-08-01 18:49:29,673 mloop.controllers    INFO     	* Best parameters found: nan
2024-08-01 18:49:29,674 mloop.controllers    INFO     	* Best cost returned: inf +/- nan
2024-08-01 18:49:29,675 mloop.controllers    INFO     	* Best run index: nan
2024-08-01 18:50:08,559 mloop.interfaces     DEBUG    Creating interface.
2024-08-01 18:50:08,559 mloop.controllers    DEBUG    Controller init completed.
2024-08-01 18:50:08,559 mloop.learners.3     DEBUG    Learner init completed.
2024-08-01 18:50:08,559 mloop.learners.4     DEBUG    Learner init completed.
2024-08-01 18:50:08,564 mloop.controllers    INFO     Optimization started.
2024-08-01 18:50:08,565 mloop.interfaces     DEBUG    Entering main loop of interface.
2024-08-01 18:50:08,565 mloop.controllers    DEBUG    ML learner started.
2024-08-01 18:50:08,619 mloop.controllers    DEBUG    Starting training optimization.
2024-08-01 18:50:08,619 mloop.controllers    INFO     Run: 0 (training)
2024-08-01 18:50:08,625 mloop.controllers    INFO     params [ 8.39488758 26.69545288  0.10545506 13.79663341  2.53894171]
2024-08-01 18:50:26,904 mloop.interfaces     DEBUG    Interface ended
2024-08-01 18:50:27,752 mloop.controllers    ERROR    The interface raised an error with traceback:
  File "c:\Users\jarjarbinks\.venv\kpy\lib\site-packages\mloop\interfaces.py", line 133, in run
    cost_dict = self.get_next_cost_dict(params_dict)

  File "c:\Users\jarjarbinks\code\k-exp\kexp\experiments\Mloop testing\integration\lib.py", line 168, in get_next_cost_dict
    cost = getCost()

  File "c:\Users\jarjarbinks\code\k-exp\kexp\experiments\Mloop testing\integration\lib.py", line 30, in getCost
    atomnumber = getAtomNumber()

  File "c:\Users\jarjarbinks\code\k-exp\kexp\experiments\Mloop testing\integration\lib.py", line 25, in getAtomNumber
    ad = load_atomdata(0,crop_type='gm',average_repeats = True)

  File "c:\users\jarjarbinks\code\k-exp\kexp\util\data\load_atomdata.py", line 71, in load_atomdata
    ad = atomdata(xvarnames,images,image_timestamps,params,camera_params,run_info,

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\atomdata.py", line 71, in __init__
    self.analyze_ods()

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\atomdata.py", line 260, in analyze_ods
    self._analyze_absorption_images(crop_type)

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\atomdata.py", line 297, in _analyze_absorption_images
    self.od, self.sum_od_x, self.sum_od_y = process_ODs(self.od_raw, crop_type, self.Nvars)

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\image_processing\compute_ODs.py", line 30, in process_ODs
    ODs = roi.crop_OD(raw_ODs,crop_type,Nvars)

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\image_processing\roi_select.py", line 73, in crop_OD
    return cropOD

2024-08-01 18:50:27,752 mloop.controllers    WARNING  Controller ended due to exception of some kind. Starting shut down...
2024-08-01 18:50:27,752 mloop.controllers    DEBUG    ML learner end set.
2024-08-01 18:50:29,352 mloop.controllers    DEBUG    ML learner joined
2024-08-01 18:50:29,352 mloop.controllers    INFO     Machine learning learner did not provide best and/or all minima.
2024-08-01 18:50:29,352 mloop.controllers    DEBUG    Learner end event set.
2024-08-01 18:50:29,352 mloop.controllers    DEBUG    Interface end event set.
2024-08-01 18:50:29,684 mloop.learners.3     DEBUG    Learner end signal received. Ending
2024-08-01 18:50:30,691 mloop.controllers    DEBUG    Learner joined.
2024-08-01 18:50:30,691 mloop.controllers    DEBUG    Interface joined.
2024-08-01 18:50:30,692 mloop.controllers    WARNING  Safely shut down. Below are results found before exception.
2024-08-01 18:50:30,693 mloop.controllers    INFO     Optimization ended because:
2024-08-01 18:50:30,694 mloop.controllers    INFO     	* Error occurred.
2024-08-01 18:50:30,695 mloop.controllers    INFO     Results:
2024-08-01 18:50:30,696 mloop.controllers    INFO     	* Best parameters found: nan
2024-08-01 18:50:30,696 mloop.controllers    INFO     	* Best cost returned: inf +/- nan
2024-08-01 18:50:30,696 mloop.controllers    INFO     	* Best run index: nan
