2025-08-12 20:52:45,870 mloop                INFO     M-LOOP version 3.3.4
2025-08-12 20:52:45,872 mloop                DEBUG    M-LOOP Logger configured.
2025-08-12 20:52:45,872 mloop.interfaces     DEBUG    Creating interface.
2025-08-12 20:52:45,873 mloop.controllers    DEBUG    Controller init completed.
2025-08-12 20:52:45,873 mloop.learners.1     DEBUG    Learner init completed.
2025-08-12 20:52:45,874 mloop.learners.2     DEBUG    Learner init completed.
2025-08-12 20:52:45,874 mloop.controllers    INFO     Optimization started.
2025-08-12 20:52:45,877 mloop.interfaces     DEBUG    Entering main loop of interface.
2025-08-12 20:52:45,877 mloop.controllers    DEBUG    ML learner started.
2025-08-12 20:52:45,980 mloop.controllers    DEBUG    Starting training optimization.
2025-08-12 20:52:45,980 mloop.controllers    INFO     Run: 0 (training)
2025-08-12 20:52:45,980 mloop.controllers    INFO     params [13.9    9.3   -0.9   12.7    0.84   0.189 12.7    0.15   0.4  ]
2025-08-12 20:52:52,854 mloop.controllers    INFO     cost -67.42592247936543 +/- 10.0
2025-08-12 20:52:52,854 mloop.controllers    INFO     Run: 1 (training)
2025-08-12 20:52:52,859 mloop.controllers    INFO     params [14.47886029  5.01739297 -0.22394036 12.6865383   1.82400085  0.105391
 13.41260877  0.14532682  0.54274533]
2025-08-12 20:52:57,464 mloop.interfaces     DEBUG    Interface ended
2025-08-12 20:52:57,908 mloop.controllers    ERROR    The interface raised an error with traceback:
  File "c:\Users\jarjarbinks\.venv\kpy\lib\site-packages\mloop\interfaces.py", line 133, in run
    cost_dict = self.get_next_cost_dict(params_dict)

  File "c:\Users\jarjarbinks\code\k-exp\kexp\experiments\Mloop testing\integration\lf_exp.py", line 256, in get_next_cost_dict
    cost = getCost()

  File "c:\Users\jarjarbinks\code\k-exp\kexp\experiments\Mloop testing\integration\lf_exp.py", line 32, in getCost
    atomnumber = getAtomNumber()

  File "c:\Users\jarjarbinks\code\k-exp\kexp\experiments\Mloop testing\integration\lf_exp.py", line 25, in getAtomNumber
    ad = load_atomdata(0,37963)

  File "c:\users\jarjarbinks\code\k-exp\kexp\util\data\load_atomdata.py", line 42, in load_atomdata
    ad = atomdata(idx,roi_id,path,

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\atomdata.py", line 101, in __init__
    self._load_data(idx,path,lite)

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\atomdata.py", line 665, in _load_data
    self.xvars = self._unpack_xvars()

  File "c:\users\jarjarbinks\code\k-exp\kexp\analysis\atomdata.py", line 570, in _unpack_xvars
    self.xvardims[i] = np.int32(len(xvars[i]))

2025-08-12 20:52:57,909 mloop.controllers    WARNING  Controller ended due to exception of some kind. Starting shut down...
2025-08-12 20:52:57,910 mloop.controllers    DEBUG    ML learner end set.
